version: '3.8'

services:
  database:
    image: postgres:12.6
    container_name: simple-remit-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    tty: true  
