name: GitHub Workflow Demo
on:
  workflow_dispatch:

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          echo "asem"
        name: eaaaa
      - run: echo "baba"
        name: 2
      - run: node main.js
