name: GitHub Workflow Demo
on:
  workflow_dispatch:

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          echo "asem"
        name: eaaaa
      - run: echo "baba"
        name: 2
      - run: node main.js
      - run: |
          REF_TYPE=${{ github.ref_type }}
          if [[ "$REF_TYPE" != "tag" ]]; then
            echo "Workflow is not run on tag."
            exit 1
          fi
          echo "Workflow is running of tag"
